  name: turfzone
  description: "A new Flutter project."

  version: 1.0.0+1

  environment:
    sdk: ^3.10.7

  dependencies:
    flutter:
      sdk: flutter

    google_fonts: ^6.1.0
    flutter_svg: ^2.0.9
    cupertino_icons: ^1.0.8
    iconsax_flutter: ^1.0.0
    video_player: ^2.8.3
    chewie: ^1.5.0
    photo_view: ^0.14.0
    url_launcher: ^6.1.12
    intl: ^0.19.0
    image_picker: ^1.0.4
    cached_network_image: ^3.4.1
    




  dev_dependencies:
    flutter_test:
      sdk: flutter

    flutter_lints: ^6.0.0
    flutter_native_splash: ^2.4.0

  flutter:
    uses-material-design: true

    assets:
      - assets/images/logo.png
      - assets/images/icons/payments/
      - assets/images/handshake.png

  flutter_native_splash:
    color: "#1DB954"
    image: assets/images/logo.png
    android: true
    ios: true

    android_12:
      color: "#1DB954"
      image: assets/images/logo.png

